######################################################################
# Automatically generated by qmake (2.01a) jue oct 18 11:14:36 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += GaussianCompleto.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
