######################################################################
# Automatically generated by qmake (2.01a) lun oct 8 11:31:43 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += histogram.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp