######################################################################
# Automatically generated by qmake (2.01a) jue oct 4 09:22:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += graya.cpp
QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp