######################################################################
# Automatically generated by qmake (2.01a) jue oct 11 08:54:06 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += sobel1.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp