######################################################################
# Automatically generated by qmake (2.01a) jue oct 18 08:54:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Gaussian.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
