######################################################################
# Automatically generated by qmake (2.01a) jue oct 18 09:36:53 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Gaussian_completo.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
