######################################################################
# Automatically generated by qmake (2.01a) vie oct 19 11:32:39 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += sobel2.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
